local_backend: true
backend:
  name: git-gateway
  branch: develop

media_folder: static/imgimg
public_folder: /img
locale: 'pl'
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: "annoucements"
    label: "Ogłoszenia"
    label_singular: "Ogłoszenie"
    description: 'Tutaj można dodawać nowe ogłoszenia duszpasterskie. UWAGA: na stronie będzie wyświetlane jedynie ostatnio dodane ogłoszenie.'
    folder: "content/annoucements"
    create: true
    slug: "ogloszenia-{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    editor:
     preview: false
    fields:
      - { label: "Typ", name: "type", widget: "hidden", default: "annoucement" }
      - { label: "Tytuł", name: "title", widget: "string", default: "ogłoszenia parafialne i duszpasterskie" }
      - { label: "Data dodania", name: "date", widget: "datetime" }
      - { label: "Treść", name: "body", widget: "markdown" }
  - name: "articles"
    label: "Artykuły"
    label_singular: "artykuł"
    description: 'Tutaj można dodawać nowe artykuły.'
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    path: '{{slug}}/index'
    editor:
     preview: false
    fields:
      - { label: "Typ", name: "type", widget: "hidden", default: "article" }
      - { label: 'Tytuł', name: 'title', widget: 'string' }
      - { label: 'Data dodania', name: 'date', widget: 'datetime' }
      - { label: 'Data wydarzenia', name: 'eventDate', default: '', widget: 'datetime', required: false }
      - { label: 'Autor', name: 'author', widget: 'select', default: ["parafia wesoła"], options: ["parafia wesoła"] }
      - { label: 'Okładka', name: 'cover', widget: image }
      - {
          label: 'Galeria',
          name: 'images',
          widget: 'list',
          required: false,
          field: { widget: image },
        }
      - { label: 'Treść', name: 'body', widget: 'markdown' }
  - name: "newsfeed"
    label: "Dzieje się"
    label_singular: "Dzieje się"
    description: 'Tutaj można zarządzać sekcją dzieje się. UWAGA!!! Na liście musi być przynajmniej jednej element, nawet pusty.'
    folder: "content/pages/dzieje_sie"
    delete: false
    editor:
     preview: false
    fields:
      - { label: "Typ", name: "type", widget: "hidden" }
      - { label: "Tytuł", name: "title", widget: "string", default: "newsfeed" }
      - label: "Dzieje się"
        name: "news"
        widget: "list"
        fields:
          - {label: Nazwa, name: title, widget: relation, collection: articles, searchFields: [title], valueField: title, default: '', required: false }
          - {label: Wielkość, name: size, widget: select, options: ["large", "medium"], default: "large" }
  - name: "crew"
    label: "Ekipa"
    label_singular: "członek ekipy"
    description: "Miejsce do zarządzania kolejnością wyświetlania czlonków ekipy w sekcjach 'o nas' i 'rada parafialna'. UWAGA!!! Osoby ustawione w sekcji 'o nas' pojawią się również w zakładce kontakt w menu"
    folder: "content/manager"
    delete: false
    editor:
     preview: false
    fields:
      - { label: "Typ", name: "type", widget: "hidden" }
      - { label: "Tytuł", name: "title", widget: "string" }
      - label: "Kolejność"
        name: "users"
        widget: "list"
        fields:
        - {label: Nazwa, name: title, widget: relation, collection: users, searchFields: [title], valueField: title, default: '', required: false }
  - name: "users"
    label: "Osoby"
    label_singular: "osoba"
    description: 'Tutaj można dodawać nowe pozycje z notkami biograficznymi.'
    folder: "content/pages"
    create: true
    filter: {field: "type", value: "user"}
    slug: "{{slug}}"
    path: '{{slug}}/index'
    editor:
     preview: false
    fields:
      - { label: "Typ", name: "type", widget: "hidden", default: "user" }
      - { label: 'Imię i nazwisko', name: 'title', widget: 'string' }
      - { label: 'Zdjęcie', name: 'cover', widget: image, required: false }
      - { label: 'Stanowisko', name: 'position', widget: 'string', required: false }
      - { label: 'Numer telefonu', name: 'phone', widget: 'string', required: false }
      - { label: 'E-mail', name: 'mail', widget: 'string', required: false }
      - { label: 'Bio', name: 'body', widget: 'markdown' }